apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
