version: "3.9"

services:
  unchained_local:
    image: ghcr.io/kenshitech/unchained:latest
    container_name: unchained_local
    hostname: unchained_local
    user: "${UID_GID}"
    volumes:
      - ./conf.local.yaml:/app/conf.yaml
    depends_on:
      - mongodb
    profiles: ["local"]
    restart: always

  postgres:
    image: postgres:16.1
    container_name: postgres
    hostname: postgres
    user: "${UID_GID}"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    profiles: ["local"]
    restart: always

  unchained_lite:
    image: ghcr.io/kenshitech/unchained:latest
    container_name: unchained_lite
    hostname: unchained_lite
    user: "${UID_GID}"
    volumes:
      - ./conf.lite.yaml:/app/conf.yaml
    profiles: ["lite"]
    restart: always

  unchained_remote:
    image: ghcr.io/kenshitech/unchained:latest
    container_name: unchained_remote
    hostname: unchained_remote
    user: "${UID_GID}"
    volumes:
      - ./conf.atlas.yaml:/app/conf.yaml
    profiles: ["remote"]
    restart: always
