version: "3.9"

services:
  unchained_local:
    image: ghcr.io/kenshitech/unchained:latest
    container_name: unchained_local
    hostname: unchained_local
    volumes:
      - ./conf.local.yaml:/app/conf.yaml
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - UNCHAINED_NODE_TYPE=full
    profiles: ["local"]
    restart: always

  postgres:
    image: postgres:16.1
    container_name: postgres
    hostname: postgres
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    profiles: ["local"]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    profiles: ["local"]
    depends_on:
      postgres:
        condition: service_healthy

  unchained_lite:
    image: ghcr.io/kenshitech/unchained:latest
    container_name: unchained_lite
    hostname: unchained_lite
    volumes:
      - ./conf.lite.yaml:/app/conf.yaml
    environment:
      - UNCHAINED_NODE_TYPE=lite
    profiles: ["lite"]
    restart: always

  unchained_remote:
    image: ghcr.io/kenshitech/unchained:latest
    container_name: unchained_remote
    hostname: unchained_remote
    volumes:
      - ./conf.remote.yaml:/app/conf.yaml
    environment:
      - UNCHAINED_NODE_TYPE=lite
    profiles: ["remote"]
    restart: always
