apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-worker
data:
  conf.worker.yaml: |
    log: info
    name: unchained-worker-k8s-test-node
    rpc:
      ethereum:
        - https://ethereum.publicnode.com
        - https://eth.llamarpc.com
        - wss://ethereum.publicnode.com
        - https://eth.rpc.blxrbdn.com
