
name: Deploy Images to GHCR

env:
  NODE_VERSION: '20.10.0'

on:
  push:
    tags:
      - v*

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: get-npm-version
            id: package-version
            uses: martinbeentjes/npm-get-version-action@v1.3.1

          - name: 'Build Inventory Image'
            env:
              UNCHAINED_VERSION: ${{ steps.package-version.outputs.current-version }}
            run: |
              docker build --build-arg NODE_VERSION=$NODE_VERSION --build-arg UNCHAINED_VERSION=$UNCHAINED_VERSION -t unchained:latest .
              docker tag unchained:latest ghcr.io/kenshitech/unchained:latest
              docker tag unchained:latest ghcr.io/kenshitech/unchained:v$UNCHAINED_VERSION
              docker push ghcr.io/kenshitech/unchained:latest
              docker push ghcr.io/kenshitech/unchained:v$UNCHAINED_VERSION
