# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'
          cache: false

      - name: Install Tools
        working-directory: "internal"
        run: make tools

      - name: Lint
        working-directory: "internal"
        run: make lint

      - name: Error Check
        working-directory: "internal"
        run: make errors
