name: Make release

on:
  push:
    tags:
      - v*
    branches:
      - go

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build
        run: cd src && make test

      - name: "Release"
        uses: softprops/action-gh-release@v1
        with:
          files: ./src/bin/*
          name: Unchained ${{ github.ref_name}}
          tag_name: ${{ github.ref_name }}
          prerelease: true
